# server port
port: 3000 
baseUrl: /webapi
# request to social media websits.
#proxy: http://proxy2.cwb.gov.tw:8888
#static file directory
staticFileDirectory: 
  webPrefix: public
  pagePrefix: public/dist
  docPrefix: ../opendatadoc


#  user login session.
jsonWebToken: 
  tokenType: Bearer
  secret: cwbopendataplatform
  refreshTokenInTime: 3000
  expiredTokenOnTime: 3600



logger: 
  infoName: info-file
  infoPath: /data/project/iisi/opendata/execute/opendataRetrievalApi/log/web-info.log
  errorName: error-file
  errorPath: /data/project/iisi/opendata/execute/opendataRetrievalApi/log/web-error.log
  # frontend error send back to serverend
  errorClientName: client-error-file
  errorClientPath: /data/project/iisi/opendata/execute/opendataRetrievalApi/log/web-client.error.log
  